// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeConfiguration(arg1) {
  return window['go']['main']['App']['ChangeConfiguration'](arg1);
}

export function CreateConfiguration(arg1, arg2) {
  return window['go']['main']['App']['CreateConfiguration'](arg1, arg2);
}

export function DeleteConfigurationFile(arg1) {
  return window['go']['main']['App']['DeleteConfigurationFile'](arg1);
}

export function GetBangumiInfo(arg1) {
  return window['go']['main']['App']['GetBangumiInfo'](arg1);
}

export function GetCurrentConfiguration(arg1) {
  return window['go']['main']['App']['GetCurrentConfiguration'](arg1);
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ScanConfiguraitonFiles() {
  return window['go']['main']['App']['ScanConfiguraitonFiles']();
}

export function SubmitVideoInfo(arg1) {
  return window['go']['main']['App']['SubmitVideoInfo'](arg1);
}
