// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {api} from '../models';

export function ChangeConfiguration(arg1:config.Config):Promise<number>;

export function CreateConfiguration(arg1:config.Config,arg2:string):Promise<string>;

export function DeleteConfigurationFile(arg1:string):Promise<number>;

export function GetBangumiInfo(arg1:string):Promise<api.Bangumi>;

export function GetCurrentConfiguration(arg1:string):Promise<config.Config>;

export function GetVideoInfo(arg1:string):Promise<api.VideoInfo>;

export function Greet(arg1:string):Promise<string>;

export function ScanConfiguraitonFiles():Promise<Array<string>>;

export function SubmitVideoInfo(arg1:api.VideoInfo):Promise<void>;
